### ISSUE TITLE
Calendar not loading

### ISSUE THREAD

**Issue by crowesn** [dsacincy/dsacincy.github.io#18]
Looks like the calendar is broken.

```
Load denied by X-Frame-Options: https://accounts.google.com/ServiceLogin?service=cl&passive=1209600&osid=1&continue=https://calendar.google.com/calendar/embed?title%3DDSA%2BCincy%2BCalendar%26showTitle%3D0%26showCalendars%3D0%26height%3D600%26wkst%3D1%26bgcolor%3D%2523FFFFFF%26src%3Ddsacincy@gmail.com%26color%3D%2523711616%26ctz%3DAmerica/New_York&followup=https://calendar.google.com/calendar/embed?title%3DDSA%2BCincy%2BCalendar%26showTitle%3D0%26showCalendars%3D0%26height%3D600%26wkst%3D1%26bgcolor%3D%2523FFFFFF%26src%3Ddsacincy@gmail.com%26color%3D%2523711616%26ctz%3DAmerica/New_York&scc=1 does not permit framing.
```

<img width="1335" alt="Screen Shot 2019-06-05 at 6 29 14 PM" src="https://user-images.githubusercontent.com/1069588/59000619-22dead00-87c0-11e9-9f76-9755a6d54db1.png">

**Comment by coopere5** [comment]
This is a known issue but one that we should probably address. This is caused by the fact that we are currently using the private version of the calendar. Creating and using a public version that mirrors the private, excluding certain events, will fix this. I'll work with the secretary this week to start getting this resolved.

**Comment by coopere5** [comment]
As a temporary fix, I'm going to grab the Facebook events widget instead, and address public calendar with #15 in the near future.

**Comment by coopere5** [comment]
There is a remaining issue with this fix, possibly related to how Facebook's scripts load that I am going to work to fix tonight. I knew I should have tested this on my own domain at home rather than trusting it would have worked at work.

**Comment by coopere5** [comment]
This is still an issue for some reason, despite testing in the coopere5 environment this time. It works differently there than here. I do not understand why.

**Comment by coopere5** [comment]
This is finally and completely fixed with no additional loading issues.
