### ISSUE TITLE
Enable/enforce HTTPS

### ISSUE THREAD

**Issue by coopere5** [dsacincy/dsacincy.github.io#8]
Soon, Google Chrome will mark all HTTP sites as "Not Secure" all the time. In order to prevent being marked as not secure, we need to set up HTTPS for the dsacincy.org domain, which GitHub Pages supports now for custom domain names as of May 2018. Related blog post: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by coopere5** [comment]
It looks we need to do a DNS level configuration change in order to make this happen: https://github.community/t5/GitHub-Pages/How-to-enable-https-support-on-custom-domains/m-p/6923#M463

**Comment by crowesn** [comment]
@coopere5 I'll take a look at this tonight.

**Comment by crowesn** [comment]
Waiting for DNS update to propogate - should be within 24 hrs.

**Comment by crowesn** [comment]
@coopere5 This appears to be resolved - not sure about our gitflow but you can feel free to close the issue.
